CrawlerSetting:
  PageStart: 1
  PageEnd: 1
  EnableProxy: true
  ProxyHost: http://127.0.0.1:62340
  TagConsumerCount: 2
  HonConsumerCount: 6
  HonBuffer: 36
  TagBuffer: 36
  EnableFilter: false
  WantedTags:
    - 百合
    - 女同士
    - Yuri
    - yuri
